### PR TITLE
Add recycled packaging information

### PR DESCRIPTION
**Pull request by LouiseBonnard**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add the recycled packaging information to the checkout process.
| Fixed ticket? | Related to https://github.com/PrestaShop/PrestaShop/issues/16348 & https://github.com/PrestaShop/prestashop-specs/pull/152#discussion_r504106782

### CODE REVIEW

**Review by Robin-Fischer-PS — CHANGES_REQUESTED** [review]
For the display of this option in confirmation (and summary and email...) : Should it be displayed only if the customer checked the "Recycled packaging" in Shipping step ? Or should it always be displayed, even if the customer did not choose this option ?

**Comment by LouiseBonnard** [comment]
You're right, @Robin-Fischer-PS, I did not mention this step in my specifications! It should be displayed only if the customer decides to receive his/her order in recycled packaging, I add it right away.

**Review by Robin-Fischer-PS — APPROVED** [review]
LGTM, thanks @LouiseBonnard :)

**Review by marionf — APPROVED** [review]

**Comment by marionf** [comment]
Thank you @LouiseBonnard !

**Pull request merged**
