### PR TITLE
Specify the disassociation in case of multiple suppliers

### PR DESCRIPTION
**Pull request by LouiseBonnard**
@marionf, @MatShir, a small precision with the current behavior in case of multiple suppliers. Disassociate a supplier resets all values. Examples below, don't mind the deep inspiration regarding the reference names, aha!

1. I have two suppliers associated with my product and the first one is my default supplier. All data are here.
Capture d’écran 2020-09-07 à 15 36 51

2. I disassociate the first supplier (and my default one) but the second one remains associated. All data have been cleared.
Capture d’écran 2020-09-07 à 15 37 01

So I've suggested, as discussed with @jolelievre for https://github.com/PrestaShop/PrestaShop/pull/20544, to improve this weird behavior for the rework of the page. Indeed, **disassociate one supplier should delete only this supplier's data** and not the other suppliers' data. Same for the deletion of a supplier in Catalog > Brands & Suppliers > Suppliers.

### CODE REVIEW

**Review by marionf — APPROVED** [review]
Do we need to create an issue or it's already fixed in the PR [#20544 ](https://github.com/PrestaShop/PrestaShop/pull/20544) ?

**Comment by LouiseBonnard** [comment]
Nope, I've added it to the specifications so that it can be done when the page will be reworked in 1.7.8. And I've just edited the description of the related issue: https://github.com/PrestaShop/PrestaShop/issues/19683.

**Comment by LouiseBonnard** [comment]
@marionf, @MatShir, you can merge it if you validate this behavior. :-)

**Comment by marionf** [comment]
All good for me, merged :tada: 
Thank you @LouiseBonnard

**Pull request merged**
