### PR TITLE
Fix for markdown typo in Contributing.md file

### LINKED ISSUE #124: The last paragraph of the contributing.md file is styled differently
In contributing.md, the last paragraph appears big and bold.

Capture d’écran 2020-08-12 à 11 44 54

It seems to come from som Markdown.

### PR DESCRIPTION
**Pull request by sam-pires**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Remove a bit of markdown making the last paragraph's text big and bold in the contributing.md file
| Type?         | refacto
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #124 
| How to test?  | Just by previewing the PR

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Thanks @sam-pires :kissing:

**Comment by matks** [comment]
Thank your for contributing @sam-pires 😄

**Comment by sam-pires** [comment]
You're welcome 😄 
Hope you are all going well!

**Comment by matks** [comment]
> You're welcome 😄
> Hope you are all going well!

Since you're gone we are unable to release 1.7.7.0 😢  you destroyed the project, man ! why did you leave 😭

**Pull request merged**
