### PR TITLE
Update ISBN part

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | ISBN need to allow numbers, spaces, hyphen and X
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/27659

Source : 

- https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s13.html
- https://fr.wikipedia.org/wiki/International_Standard_Book_Number

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@okom3pom Thank you for your contribution. But you have done the change on a template page.

Could you revert these changes ? And modify on the page `content/1.7/back-office/catalog/products/add-edit.md` ?

**Comment by okom3pom** [comment]
Done @Progi1984 && @atomiix

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Now. The ball :soccer: is on the @PrestaShop/product-team & @PrestaShop/qa-team sides.

**Review by hibatallahAouadni — CHANGES_REQUESTED** [review]

**Comment by okom3pom** [comment]
Done @hibatallahAouadni

**Review by hibatallahAouadni — APPROVED** [review]
@okom3pom thanks :relaxed:

**Comment by MatShir** [comment]
Thanks @okom3pom, the third will be the one ! close this PR in favor of https://github.com/PrestaShop/prestashop-specs/pull/349

**Comment by okom3pom** [comment]
Thank you @MatShir 

Don't hesitate to tell me next time, I like to accomplish : 

Issue --> Spec --> Doc --> PR or in other order :)

**Pull request closed without merging**
