### PR TITLE
Authorized ip address in maintenance mode

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add specs for authorized ip address in maintenance mode
| Fixed ticket? | no ticket

### CODE REVIEW

**Comment by marionf** [comment]
Hello @jf-viguier 

Thank you for your PR :+1: 

As this change concerns mainly the possibility to add an IP V6 in the maintenance page of the back-office, could you please specify this rather in https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/shop-parameters/general/maintenance.md ?

**Comment by jf-viguier** [comment]
@marionf indeed but the main impact is in front. Would you like in both side ?

**Comment by jf-viguier** [comment]
@marionf done https://github.com/PrestaShop/prestashop-specs/pull/235

**Comment by marionf** [comment]
Great, thank you @jf-viguier !

**Pull request merged**
