### PR TITLE
Specify empty search results behaviors

### PR DESCRIPTION
**Pull request by LouiseBonnard**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Write down the messages to display when any visitor reaches empty search results. @Julievrz, feel free to complete this file if need be with the different use cases, etc.
| Fixed ticket? | Specify https://github.com/PrestaShop/PrestaShop/issues/15118.

### CODE REVIEW

**Comment by Julievrz** [comment]
It looks very clear to me!☺️

**Review by marionf — APPROVED** [review]
Very clear :)

**Comment by Robin-Fischer-PS** [comment]
LGTM, thanks @LouiseBonnard :)

**Review by Robin-Fischer-PS — APPROVED** [review]

**Comment by marionf** [comment]
Muchas gracias @LouiseBonnard

**Pull request merged**
