### PR TITLE
Add information to the Webservice specifications

### PR DESCRIPTION
**Pull request by LouiseBonnard**
A few additions to your specifications, @MatShir, I let you review them and merge the PR whenever you decide. One suggestion: the 'Key description' field does not look limited in characters, should it be?

### CODE REVIEW

**Comment by MatShir** [comment]
I agree with you, we could have 250 characters

**Comment by MatShir** [comment]
https://github.com/PrestaShop/PrestaShop/issues/22536 here the issue with the improvement.

**Comment by LouiseBonnard** [comment]
Actually, I was talking about the 'Key description' field which is not limited in characters, the 'Key' field is limited to 32 characters.

**Comment by marionf** [comment]
@MatShir I added some details about the multistore :)

**Comment by Robin-Fischer-PS** [comment]
OK for me ;)

**Comment by marionf** [comment]
@LouiseBonnard Woops, there are conflicts, could you resolve them ?

**Comment by LouiseBonnard** [comment]
Still waiting for @MatShir's review.

**Comment by MatShir** [comment]
Nice 😄

**Pull request merged**
