### PR TITLE
Enable store for logged-in employees

### PR DESCRIPTION
**Pull request by LouiseBonnard**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Allow logged-in employees to access the front office while the store is in maintenance mode.
| Fixed ticket? | Related to https://github.com/PrestaShop/PrestaShop/issues/18932.

### CODE REVIEW

**Comment by LouiseBonnard** [comment]
@Julievrz, feel free to challenge this wording - or any wording of the _Shop Parameters > Maintenance_ page if you spot some inconsistencies. :-)

**Review by marionf — APPROVED** [review]

**Comment by Julievrz** [comment]
> @Julievrz, feel free to challenge this wording - or any wording of the _Shop Parameters > Maintenance_ page if you spot some inconsistencies. :-)

This wording looks good to me. However, I have a few suggestions for the rest of the page. 

First of all, I think we should replace "shop" with "store" everywhere on the page for more consistency. 

Secondly, I suggest modifying the help texts:

image
=> Allow authorized IP addresses to access the front office while the store is in maintenance mode. Please use a comma to separate them (e.g. 42.24.4.2,127.0.0.1,99.98.97.96)

And this one:

**Comment by Julievrz** [comment]
> @Julievrz, feel free to challenge this wording - or any wording of the _Shop Parameters > Maintenance_ page if you spot some inconsistencies. :-)

I like this wording. However, I have a few suggestions for the rest of the page.

First of all, I think we should replace "shop" with "store" everywhere on the page for more consistency.

Secondly, I think we could modify the help texts:

image
=> We recommend that you deactivate your store while performing maintenance. Please note that the webservice will not be disabled.

image
=> Allow authorized IP addresses to access the front office while the store is in maintenance mode. Please use a comma to separate them (e.g. 42.24.4.2,127.0.0.1,99.98.97.96).

image
=> Write a personalized message for the customers to read when the store is deactivated. 

Wdyt @LouiseBonnard ? 😊

**Comment by LouiseBonnard** [comment]
Hey, thanks for the review, @Julievrz!

> First of all, I think we should replace "shop" with "store" everywhere on the page for more consistency.

I fully agree, I've changed it everywhere the wording needs to be rewritten. See https://github.com/PrestaShop/prestashop-specs/pull/183/commits/dd4a44097562c170e09d6401df62efde2aec79bf and https://github.com/PrestaShop/prestashop-specs/pull/183/commits/0b96a527450b8bcc0da83dfef40f79c0c2af2d0e.

Okay for the tooltips (to be turned as help texts), I've tried to shorten them whenever it was possible. I've kept the former tooltip for the IP addresses feature as it is shorter and clear enough. I let you review it once again and let me know if it is all fine for you. ;-)

**Comment by Julievrz** [comment]
> Hey, thanks for the review, @Julievrz!
> 
> > First of all, I think we should replace "shop" with "store" everywhere on the page for more consistency.
> 
> I fully agree, I've changed it everywhere the wording needs to be rewritten. See [dd4a440](https://github.com/PrestaShop/prestashop-specs/commit/dd4a44097562c170e09d6401df62efde2aec79bf) and [0b96a52](https://github.com/PrestaShop/prestashop-specs/commit/0b96a527450b8bcc0da83dfef40f79c0c2af2d0e).
> 
> Okay for the tooltips (to be turned as help texts), I've tried to shorten them whenever it was possible. I've kept the former tooltip for the IP addresses feature as it is shorter and clear enough. 

**No problem, it is true that it is shorter.  I just thought that it might have been good to use the same sentence construction as the new one. But I am fine with keeping the old wording.**

**Review by Robin-Fischer-PS — APPROVED** [review]

**Comment by marionf** [comment]
Thank you @LouiseBonnard, @Julievrz and @Robin-Fischer-PS for the review :tada:

**Pull request merged**
